### ISSUE TITLE
Unable to run CellProfiler from containing directory

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/distribution#2]
`/Applications/CellProfiler/CellProfiler.app/Contents/MacOS/CellProfiler` works but

```
cd /Applications/CellProfiler/CellProfiler.app/Contents/MacOS
CellProfiler
```

fails with

```
Traceback (most recent call last):
  File "/usr/local/bin/CellProfiler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3058, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CellProfiler' distribution was not found and is required by the application
```

**Comment by AnneCarpenter** [comment]
@mcquin says it is the same whether from DMG or /Applications
